import { afterEach, describe, expect, it, vi } from "vitest";
import { checkDevSessionEnv, neonEndpoint } from "./dev-session-guard";

// Realistic shapes of the two Neon branch URLs: pooled dev endpoint, direct test endpoint.
// They differ in the endpoint id (ep-dev-111 vs ep-test-222), which is what the guard compares.
const DEV_URL = "postgresql://u:p@ep-dev-111-pooler.eu-central-1.aws.neon.tech/db?sslmode=require";
const TEST_URL = "postgresql://u:p@ep-test-222.eu-central-1.aws.neon.tech/db?sslmode=require";
const DEV_ENV = `# Generated by devspace\nDATABASE_URL="${DEV_URL}"\nAUTH_SECRET="dev-secret"\n`;
const TEST_ENV = `DATABASE_URL="${TEST_URL}"\n`;

describe("neonEndpoint", () => {
  it("strips the pooler suffix so pooled and direct URLs of one branch compare equal", () => {
    expect(neonEndpoint(DEV_URL)).toBe("ep-dev-111");
    expect(neonEndpoint("postgresql://x:y@ep-dev-111.eu-central-1.aws.neon.tech/other")).toBe("ep-dev-111");
  });

  it("falls back to the host name for non-Neon hosts", () => {
    expect(neonEndpoint("postgresql://u:p@localhost:5432/db")).toBe("localhost");
  });

  it("returns null for text that is not a URL", () => {
    expect(neonEndpoint("not a url")).toBeNull();
  });
});

describe("checkDevSessionEnv", () => {
  afterEach(() => vi.unstubAllEnvs());

  it("returns .env's values when dev and test are different branches", () => {
    expect(checkDevSessionEnv({ devEnvText: DEV_ENV, testEnvText: TEST_ENV, nodeEnv: "development" })).toEqual({
      ok: true,
      databaseUrl: DEV_URL,
      authSecret: "dev-secret",
    });
  });

  it("refuses when .env and .env.test point at the same Neon endpoint, pooled or not", () => {
    const sameBranch = `DATABASE_URL="postgresql://other:pw@ep-dev-111.eu-central-1.aws.neon.tech/db"\n`;
    const result = checkDevSessionEnv({ devEnvText: DEV_ENV, testEnvText: sameBranch, nodeEnv: undefined });
    expect(result.ok).toBe(false);
    expect(!result.ok && result.reason).toMatch(/same Neon endpoint/);
  });

  it("refuses when NODE_ENV is production", () => {
    const result = checkDevSessionEnv({ devEnvText: DEV_ENV, testEnvText: TEST_ENV, nodeEnv: "production" });
    expect(!result.ok && result.reason).toMatch(/production/);
  });

  it("refuses without .env", () => {
    const result = checkDevSessionEnv({ devEnvText: null, testEnvText: TEST_ENV, nodeEnv: undefined });
    expect(!result.ok && result.reason).toMatch(/\.env is missing/);
  });

  it("refuses without AUTH_SECRET, or with an empty one", () => {
    for (const devEnvText of [`DATABASE_URL="${DEV_URL}"\n`, `DATABASE_URL="${DEV_URL}"\nAUTH_SECRET=""\n`]) {
      const result = checkDevSessionEnv({ devEnvText, testEnvText: TEST_ENV, nodeEnv: undefined });
      expect(!result.ok && result.reason).toMatch(/AUTH_SECRET/);
    }
  });

  it("refuses a missing or non-URL DATABASE_URL", () => {
    for (const devEnvText of [`AUTH_SECRET="s"\n`, `DATABASE_URL="nope"\nAUTH_SECRET="s"\n`]) {
      const result = checkDevSessionEnv({ devEnvText, testEnvText: TEST_ENV, nodeEnv: undefined });
      expect(!result.ok && result.reason).toMatch(/DATABASE_URL/);
    }
  });

  it("allows a missing .env.test (nothing to compare against)", () => {
    expect(checkDevSessionEnv({ devEnvText: DEV_ENV, testEnvText: null, nodeEnv: undefined }).ok).toBe(true);
  });

  it("uses only the file text, never process.env", () => {
    vi.stubEnv("DATABASE_URL", TEST_URL);
    vi.stubEnv("AUTH_SECRET", "process-secret");
    const result = checkDevSessionEnv({ devEnvText: DEV_ENV, testEnvText: TEST_ENV, nodeEnv: undefined });
    expect(result).toEqual({ ok: true, databaseUrl: DEV_URL, authSecret: "dev-secret" });
  });
});
